Add possibility to add ALIAS DNS record
atomia/atomiadns pull request #51
Opened 2019-07-16 13:07 UTC by milica-spasic

Added possibility to add ALIAS DNS record.

Resolves PROD-1918. (3/3)

ChangeLog:
* [ADD] Added possibility to add ALIAS DNS records

2019-08-01 12:42 UTC, stefan-stankovic-atomia requested changes

2019-08-01 12:42 UTC, stefan-stankovic-atomia commented on server/debian/atomiadns-database.postinst
> +				execute_query "INSERT INTO allowed_type (type, synopsis, regexp) VALUES ('ALIAS', 'hostname', '^[a-z0-9_][a-z0-9._-]*$')"
Add this in ddl.sql scheme file. Otherwise, it won't work after clean installation.

2019-08-14 13:54 UTC, sasa-mladenovic-troxo approved these changes

2019-08-27 12:23 UTC, sasa-mladenovic-troxo approved these changes

2019-08-27 12:25 UTC, stefan-stankovic-atomia approved these changes

2019-08-27 12:25 UTC, merged