Remove  NET::DNS::ZoneFile::Fast dependency
atomia/atomiadns pull request #54
Opened 2020-12-02 12:26 UTC by jovana-stamenkovic-atomia

Moved from NET::DNS::ZoneFile::Fast to NET::DNS::ZoneFile.

Amends PROD-2490.

2020-12-02 15:01 UTC, sasa-mladenovic-troxo requested changes

2020-12-02 15:01 UTC, sasa-mladenovic-troxo commented on zonefileimporter/debian/changelog
> +atomiadns-dyndns (1.1.49) hardy; urgency=low
```suggestion
atomiadns-zoneimport (1.1.49) hardy; urgency=low
```

2020-12-02 15:01 UTC, sasa-mladenovic-troxo commented on webapp/debian/changelog
> +atomiadns-dyndns (1.1.49) hardy; urgency=low
```suggestion
atomiadns-webapp (1.1.49) hardy; urgency=low
```

2020-12-02 15:01 UTC, sasa-mladenovic-troxo commented on syncer/debian/changelog
> +atomiadns-dyndns (1.1.49) hardy; urgency=low
```suggestion
atomiadns-nameserver (1.1.49) hardy; urgency=low
```

2020-12-02 15:01 UTC, sasa-mladenovic-troxo commented on server/debian/changelog
> +atomiadns-dyndns (1.1.49) hardy; urgency=low
```suggestion
atomiadns-masterserver (1.1.49) hardy; urgency=low
```

2020-12-02 15:01 UTC, sasa-mladenovic-troxo commented on powerdns_sync/debian/changelog
> +atomiadns-dyndns (1.1.49) hardy; urgency=low
```suggestion
atomiadns-powerdnssync (1.1.49) hardy; urgency=low
```

2020-12-03 11:54 UTC, stefan-stankovic-atomia approved these changes

2020-12-03 12:02 UTC, sasa-mladenovic-troxo approved these changes

2020-12-03 12:07 UTC, merged